
services:
  db:
    image: postgres:latest
    container_name: lib_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data

volumes:
  pgdbdata:
    driver: local