spring:
  application:
    name: BookLibrary
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true